### ISSUE TITLE
bacon.Sound() throws UnknownError when passed an non-existant file

### ISSUE THREAD

**Issue by stalepancakes** [aholkner/bacon#47]
```
Traceback (most recent call last):
  File "pyweek17.py", line 43, in <module>
    'squeak': bacon.Sound('res/squeak.wav'),
  File "c:\development\pyweek-17\bacon\sound.py", line 33, in __init__
    lib.LoadSound(byref(handle), resource.get_resource_path(file).encode('utf-8'), flags)
  File "c:\development\pyweek-17\bacon\core.py", line 142, in f
    raise BaconError._from_error_code(result)
bacon.core.UnknownError
Exception AttributeError: "'Sound' object has no attribute '_handle'" in <boundmethod Sound.__del__ of <bacon.sound.Sound object at 0x039E7AF0>> ignored
```

**Comment by aholkner** [comment]
Also images and fonts.

**Comment by aholkner** [comment]
All log error messages and raise IOError, and don't throw additional error on destruction.
